"""change name

Revision ID: 434bd31e3034
Revises: 7374e0682a8e
Create Date: 2026-04-13 15:40:04.505199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '434bd31e3034'
down_revision: Union[str, Sequence[str], None] = '7374e0682a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentences', 'name',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentences', 'name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=True)
    # ### end Alembic commands ###
