"""add_conect_between_users_and_chucks

Revision ID: 4bc05f164275
Revises: e3398ef88014
Create Date: 2026-04-26 21:01:04.853499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc05f164275'
down_revision: Union[str, Sequence[str], None] = 'e3398ef88014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chunck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunck_id'], ['chuncks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chunck_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relation')
    # ### end Alembic commands ###
