"""agein change name and url

Revision ID: 60cc757c7f4b
Revises: c89bbada99c1
Create Date: 2026-04-13 19:04:25.108938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60cc757c7f4b'
down_revision: Union[str, Sequence[str], None] = 'c89bbada99c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chuncks', 'url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('sentences', 'url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('sentences', 'name',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentences', 'name',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('sentences', 'url',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('chuncks', 'url',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
