"""change-in-model-user

Revision ID: 892caa39ae76
Revises: 48e05896df9c
Create Date: 2026-04-30 13:01:39.291910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892caa39ae76'
down_revision: Union[str, Sequence[str], None] = '48e05896df9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='users_before_indentefication')
    op.drop_index(op.f('username'), table_name='users_before_indentefication')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('username'), 'users_before_indentefication', ['username'], unique=True)
    op.create_index(op.f('email'), 'users_before_indentefication', ['email'], unique=True)
    # ### end Alembic commands ###
