"""add tabel users_before_indentefication

Revision ID: 93a35c6e5aab
Revises: ab6fc649d452
Create Date: 2026-04-23 18:45:32.381539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a35c6e5aab'
down_revision: Union[str, Sequence[str], None] = 'ab6fc649d452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
