"""add_name_for_chunck

Revision ID: 9f3abdc09dcb
Revises: 892caa39ae76
Create Date: 2026-05-11 16:36:04.086712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3abdc09dcb'
down_revision: Union[str, Sequence[str], None] = '892caa39ae76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chuncks', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chuncks', 'name')
    # ### end Alembic commands ###
